### ISSUE TITLE
usage instructions

### ISSUE THREAD

**Issue by pilchat** [rvbCMTS/PySkinDose#27]
Hi,

I have succesfully installed PySkinDose in my windows machine. Now I would like to run it: is there any user manual with some example code?

Thanks

**Comment by MaxHellstrom** [comment]
Hi!
We are planning to release several example usage scripts shortly.

But have you tried running any of the scripts in test/manual_tests? That is a good place to start.

**Comment by Witty159** [comment]
Hi,

I have problems too. I tryed to get started with the test files but for example using 
/manual_test_all_modes.py' leads to
saving static dosemaps:   0%|          | 0/4 [00:00<?, ?it/s]   
and nothing happens anymore.  Can you create a step-by-step guide on how to import your own RDSR and create 2 and 3D maps? What adjustments are necessary? What corrections need to be created etc.

For which systems does the import of the RDSR work?
Thanks

**Comment by BwKodex** [comment]
Hi @Witty159 
We're still working on the user manual with, e.g., info on how to go about running it with custom RDSR-parsing.

PySkinDose is, at the moment, tested for Siemens Axiom Artis and Phillips Allura CLarity. Please correct me if I'm wrong @MaxHellstrom 

A couple of questions about your problem.

1. Do you get any error messages  when running `manual_test_all_modes.py` that you could include here to help us find out what's going wrong?
2. What manufacturer and model do you have?

**Comment by Witty159** [comment]
Hi again,

there is no error code, it seems that the code hangs at this point.
I'm using windows 10 with the newest python anaconda package. I tried using Spyder, jupyter lab, and PyCharm.
So far i have not read in my own rdsr and use the ones that came with the installation.

We have Siemens Artis Zee and Philips Allura Xper.
Thank you for your help and all the work that went into this beautiful project!

**Comment by MaxHellstrom** [comment]
Hi @Witty159

Thank you for notifying us about this issue. Information like this is very appreciated. I'll get back to you after some testing. 
@BwKodex , yes, PySkinDose supports Siemens Axiom Artis and Phillips Allura Clarity at the moment, but there is currently a bug in Allura compliance that I am addressing now. 

I'll get back to you,

Max

**Comment by Witty159** [comment]
Hi @MaxHellstrom,

it's been a while. Have you been able to find out anything so far?

Greetings

Witty159

**Comment by Witty159** [comment]
Hi all,

again a short error report.

The error mentioned above is still present:
/manual_test_all_modes.py' leads to
saving static dosemaps: 0%| | 0/4 [00:00<?, ?it/s]


Now the following code workes for the S1.dcm but not for philips allura RDSR
The code:

from base_dev_settings import DEVELOPMENT_PARAMETERS
from pyskindose import constants
from pyskindose.main import main
from pyskindose.settings_pyskindose import PyskindoseSettings

settings = PyskindoseSettings(settings=DEVELOPMENT_PARAMETERS)
settings.mode = constants.MODE_CALCULATE_DOSE
settings.plot.interactivity = True
settings.plot.plot_dosemap = True

settings.rdsr_filename='philips_allura_clarity_u104.dcm'
main(settings=settings)

Error:
Traceback (most recent call last):
  File "C:\Users\NTBO203\Downloads\PySkinDose-master2\PySkinDose-master\tests\manual_tests\test.py", line 13, in <module>
    main(settings=settings)
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\main.py", line 44, in main
    _ = analyze_data(normalized_data=data_norm, settings=settings)
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\analyze_data.py", line 42, in analyze_data
    patient, output = calculate_dose(normalized_data=normalized_data, settings=settings, table=table, pad=pad)
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\calculate_dose\calculate_dose.py", line 84, in calculate_dose
    k_tab = calculate_k_tab(
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\corrections.py", line 227, in calculate_k_tab
    k_tab[event] = c.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

Perhapse you can help me.

Greetings

Witty159

**Comment by BwKodex** [comment]
Hi @Witty159,
I've tried to look into your problem a bit. The first error seems to me as it might have to do with the filesystem. At the moment, the code tries to save the images into the same folder as the one where you run your code, when I did my test run this was the _manual_tests_ directory of my cloned copy of PySkinDose. Perhaps the plotly function used to save the static dose map freezes here. I'll look into adding a setting for where the output file should be directed so that one can make sure that the runner has write/modify permissions to that directory

Regarding the second error (TypeError: 'NoneType' object is not subscriptable), I've checked it and it seems to be a mismatch between how the Allura Clarity model is specified in the corrections database and in the DICOM file, which leads to no data being found for the parameters sent to the query. We will add a fix for this as soon as possible.

Regarding the PSD level/value, are you referring to a calculation done on the example file _philips_allura_calrity_u104.dcm_?

As for the last question. I'm not sure I understand in what way you want to optimize the geometry. In what way do you want to shift the beam? 

PySkinDose utilizes a geometry PySkinDose relative to the source (or the iso-centre). Any translations performed are made relative to the iso-centre. So you can add translations to the table by the normalization settings and can move the patient relative the table.

**Comment by Witty159** [comment]
Hi @BwKodex,

thank you for your quick response. 
Concerning the first error:
I also run the code in my download folder and started PyCharm with admin rights.

Regarding the PSD level, I'm talking about a custom rdsr file, where a quick handmade estimation leads to higher PSD (0.3 Gy vs 6 Gy). It's a rdsr from a Allura Clarity model and only works with:
settings.estimate_k_tab=True

The PSD levels for custom rdsr from a siemens axiom artis model looks good.

**Comment by Witty159** [comment]
Again,
a new problem:

The code:

from base_dev_settings import DEVELOPMENT_PARAMETERS
from pyskindose import constants
from pyskindose.main import main
from pyskindose.settings_pyskindose import PyskindoseSettings

settings = PyskindoseSettings(settings=DEVELOPMENT_PARAMETERS)
settings.mode = constants.MODE_CALCULATE_DOSE
settings.plot.interactivity = True
settings.plot.plot_dosemap = True
settings.estimate_k_tab=True
settings.rdsr_filename='philips_allura_clarity_u601.dcm'
settings.phantom.patient_offset.d_lat=0

main(settings=settings)

and the error:

Traceback (most recent call last):
  File "C:\Users\NTBO203\Downloads\PySkinDose-master2\PySkinDose-master\tests\manual_tests\manual_test_calculate_dose_static.py", line 15, in <module>
    main(settings=settings)
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\main.py", line 44, in main
    _ = analyze_data(normalized_data=data_norm, settings=settings)
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\analyze_data.py", line 42, in analyze_data
    patient, output = calculate_dose(normalized_data=normalized_data, settings=settings, table=table, pad=pad)
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\calculate_dose\calculate_dose.py", line 75, in calculate_dose
    normalized_data = fetch_and_append_hvl(data_norm=normalized_data)
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\geom_calc.py", line 243, in fetch_and_append_hvl
    hvl = [
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pyskindose\geom_calc.py", line 244, in <listcomp>
    float(
  File "C:\Users\NTBO203\anaconda3\lib\site-packages\pandas\core\series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>

Process finished with exit code 1

perhapse you can help me again, sorry for all the questions

**Comment by Witty159** [comment]
Hi @MaxHellstrom @BwKodex ,

it's been a while. Have you been able to find out anything so far?

Greetings

Witty159

**Comment by BwKodex** [comment]
Hi @Witty159,
I'm sorry about the delay. I've been on parental leave for a while. I'll try to look into your new error as soon as possible. I have a suspicion on what might have caused the error but I'll have to investigate it further.

I've just created a release (v22.5.1) with a fix for a previous error you reported with the Allura Clarity system

**Comment by gustavega** [comment]
Hi @BwKodex i need help with pyskindose . I tryed to get started with the test files and send me error pandas.errors.DatabaseError: Execution failed on sql 'SELECT * FROM hvl_combined': no such table: hvl_combined

**Comment by BwKodex** [comment]
Hi @gustavega,
That seems like an error I've encountered recently where the actual, that should be created the first run, is not found so that an empty SQLite database is queried instead. I'm looking into fixing this bug.

**Comment by hgrover44** [comment]
> Hi @gustavega, That seems like an error I've encountered recently where the actual, that should be created the first run, is not found so that an empty SQLite database is queried instead. I'm looking into fixing this bug.

Hello @BwKodex, I am also new to using PySkinDose, and have run into a similar problem. Currently I am using the DEVELOPMENT_PARAMETERS (slightly tweaked) for the PyskindoseSettings and the most basic commands. I just wanted to see if there is a temporary work-around or alternative way to do a dose calculation while this bug is addressed? Is there some setting I can turn off or hard-coded number/file I can use in place of this lookup? I have tried digging around without much luk yet and wanted to ask here as well. Thank you!

**Comment by BwKodex** [comment]
Hi @gustavega and @hgrover44 

There is now a PR (#56) for fixing the problem with the path of the corrections db-file being wrong when running the script.

The workaround before this is merged would be to find the path of the db-file and the path where PySkinDose expects to find it later on (when it crashes) and copy the database file to that location. A bit cumbersome but doable. I've used that myself as a temporary fix for our dose monitoring systems (REMbox) integration with PySkinDose.

**Comment by gustavega** [comment]
Hi @BwKodex  , this release work !!! thanks , in another question  i try use for my locals RDSR, modified the file "base_dev_settings" but only modified in file name line. The question is about if  i need modified another settings in the file or another step in other file ? 
thanks

**Comment by BwKodex** [comment]
@gustavega: Great! Nice to know that it's working now :)

Depending on which vendor and model the machine that your file comes from you might have to modify the normalization settings to match the correct values for that machine. The normalization settings are used for telling PySkinDose any translation offset that needs to be applied to the table position and in which direction the table moves when the table position values change.

**Comment by MaxHellstrom** [comment]
Hi @gustavega,

We are currently working on normalization and compliance for additional models beyond the AXIOM Artis and Allura Clarity systems. We’ve encountered some normalization bugs, but they should be resolved and merged into the main branch soon (PR #60).

We haven’t had the chance to review an Artis Q model yet. Would it be possible for you to anonymize your Artis Q RDSR file and send it via email so I can take a look?

Thanks in advance!

**Comment by gustavega** [comment]
Hi Max, would shared your email ? i think  i would shared my another two models Artis Zee and Artis One. I send you SR for Artis Q
[IM-0001-1124-0001.dcm.zip](https://github.com/user-attachments/files/17461692/IM-0001-1124-0001.dcm.zip)

**Comment by MaxHellstrom** [comment]
Hi again, thanks so much! I’ll take a look later tonight and get back to you as soon as I can.

**Comment by gustavega** [comment]
Yes, the commercial name in my country is Artis Q, Artis Zee and Artis One. I think all models  is one family for Siemens "Axiom-Artis" . 
I dont have errors, the results  for this models is in the position, for example position X Y Z  the patient. In the script "base_dev_settings.py" i modified the line "c.OFFSET_LATERAL_KEY"  for value i think is correct for ubication for the antomical region, another option is in the "normalization_settings.json" line "Z" translation. But i i dont know what is the correct value  depend for my SR file. 
shared the other model "artis One"
[IM-0001-1124-0001.dcm.zip](https://github.com/user-attachments/files/17465919/IM-0001-1124-0001.dcm.zip)

**Comment by MaxHellstrom** [comment]
Thanks for your reply!

Could you please try the following script? Just add a new test under test/manual tests.

This script adjusts the patient’s position by moving them 10 cm down from the table top and 10 cm to the right of the table’s center line:


```
from base_dev_settings import DEVELOPMENT_PARAMETERS
from pyskindose import constants
from pyskindose.main import main
from pyskindose.settings import PyskindoseSettings
from pathlib import Path
settings = PyskindoseSettings(settings=DEVELOPMENT_PARAMETERS)
settings.mode = constants.MODE_PLOT_SETUP

file_path = Path(r'PATH_TO_YOUR_RDSR_FILE')

# move patient position upon the table:
settings.phantom.patient_offset.d_lat = -10 # move patient in Z - lat dir 
settings.phantom.patient_offset.d_lon = -10 # move patient in x - lon dir 

main(settings=settings, file_path=file_path)

``` 

Regarding normalization: 

We just fixed a bug (#60) that prevented the user to manually adding their own normalization. You can change the normalization tags by adding the following to the code above ( and run it with settings.mode = constants.MODE_PLOT_PROCEDURE) to confirm correct results.

```
# this section will change the origin a cm in all three directions.
settings.normalization_settings.trans_offset.x = a
settings.normalization_settings.trans_offset.y = a
settings.normalization_settings.trans_offset.z = a

# this section will change positive direction in direction x (similarity for y and z)
settings.normalization_settings.trans_dir.x = 1 or -1
```
Please try running the code above and let me know if it works for you. I hope it brings more clarity to the process.

Additionally, you can adjust the patient’s orientation by setting `settings.phantom.patient_orientation` to either "head_first_supine" or "feet_first_supine".

**Comment by MaxHellstrom** [comment]
some clarifications: 

The issue with some machines is that the table position tags are referenced relative to an unknown origin. To resolve this, we use a normalization_json file in PySkinDose to map the origin (i.e., the head end of the patient support table) to the origin of the table position tags in the RDSR file.

For certain models, like AXIOM-Artis, the origin in the DICOM tags aligns perfectly with the expected origin, which is why the translation offset tags for AXIOM-Artis are set to (0, 0, 0).

However, this isn’t the case for all models. For example, with the Allura Clarity, the offset must be set to (-0.3, 105.5, -173.35) to correctly align the table’s actual position (0, 0, 0) with the corresponding point in PySkinDose.

If these values don’t match your system, you can measure and determine the correct offsets yourself, then adjust the normalization as outlined in my previous post.

We’re working on improving the clarity of the normalization process for skin dose mapping in future documentation, including upcoming guides and use cases. Additionally, we plan to release a new “Getting Started” notebook later this week.

Best regards,
Max

**Comment by gustavega** [comment]
Great! @MaxHellstrom , the script run good! i run for the other models and fix the position. The other code for normalization is not necessary in this time. I run correctly pyskindose. 
Thanks From the Costa Rica...

**Comment by gustavega** [comment]
Hi again, @BwKodex i have error in this SR file of my institution i try learn what is the problem  you have any idea? ...thanks 
[Uploading SR.dcm.zip…]()

**Comment by BwKodex** [comment]
Hi @gustavega ,
Your uploading of the file does not seem to have worked and before you try it again I would just like you to confirm that it does not contain any sensitive data.

**Comment by gustavega** [comment]
Hi @BwKodexel the file is anonymize for you thanks for your time. 
 
[SR.dcm.zip](https://github.com/user-attachments/files/17717381/SR.dcm.zip)

**Comment by gustavega** [comment]
Hi @BwKodex  i think the problem is HVL  index this the error in my console
raceback (most recent call last):
  File "/opt/miniconda3/lib/python3.11/site-packages/pyskindose/tests/manual_tests/manual_test_all_modes.py", line 1, in <module>
    import manual_test_calculate_dose_interactive
  File "/opt/miniconda3/lib/python3.11/site-packages/pyskindose/tests/manual_tests/manual_test_calculate_dose_interactive.py", line 12, in <module>
    main(settings=settings)
  File "/opt/miniconda3/lib/python3.11/site-packages/pyskindose/main.py", line 53, in main
    _ = analyze_data(normalized_data=data_norm, settings=settings)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/pyskindose/analyze_data.py", line 54, in analyze_data
    patient, output = calculate_dose(normalized_data=normalized_data, settings=settings, table=table, pad=pad)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/pyskindose/calculate_dose/calculate_dose.py", line 75, in calculate_dose
    normalized_data = fetch_and_append_hvl(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/pyskindose/geom_calc.py", line 247, in fetch_and_append_hvl
    hvl = [
          ^
  File "/opt/miniconda3/lib/python3.11/site-packages/pyskindose/geom_calc.py", line 249, in <listcomp>
    hvl_data.loc[
  File "/opt/miniconda3/lib/python3.11/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/pandas/core/indexing.py", line 1752, in _getitem_axis
    self._validate_integer(key, axis)
  File "/opt/miniconda3/lib/python3.11/site-packages/pandas/core/indexing.py", line 1685, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
Error al ejecutar el comando: Command '['python3.11', 'manual_test_all_modes.py']' returned non-zero exit status 1.

**Comment by MaxHellstrom** [comment]
> Hi @BwKodex the file is anonymize for you. thanks for your time.
> 
> [SR.dcm.zip](https://github.com/user-attachments/files/17717381/SR.dcm.zip)

I’m unfortunately unable to open the attached file.

**Comment by gustavega** [comment]
Hi @MaxHellstrom and @BwKodex i submit again the SR file. I submit two files with same error , from the same machine. I hope you can help me. The files is anonymize for sensible data. 
[No_Name.zip](https://github.com/user-attachments/files/17775528/No_Name.zip)

**Comment by BwKodex** [comment]
Hi,
I managed to open the previous file. The problem I think you might have gotten Max was that the file ending .zip was incorrect. It was an uncompressed DICOM file.

@gustavega: It seems like you have exposures in your RDSR-file that has 0 kVp. In the parsed data it is the rows with index 94 and 166. The HVL-determination fails here as we don't have any HVL-value for 0 kVp.

You can get around this by writing you own version of the main-function where you either remove the rows with 0 kVp or replace them with an allowed kVp-value before calling the `analyze_data` function.

Me and Max will have to discuss how to add a fix so that these kind of errors. Perhaps with a setting and printing a warning so that it is clear how any rows are affected by the fix when running for a file.

**Comment by BwKodex** [comment]
You can rewrite the main function so that it looks something like this

```python
from typing import Optional, Union

from pyskindose import PyskindoseSettings, analyze_data
from pyskindose.helpers.parse_settings_to_settings_class import parse_settings_to_settings_class
from pyskindose.helpers.read_and_normalize_rdsr_data import read_and_normalise_rdsr_data


def new_main(file_path: Optional[str] = None, settings: Union[str, dict, PyskindoseSettings] = None):
    settings = parse_settings_to_settings_class(settings=settings)

    data_norm = read_and_normalise_rdsr_data(rdsr_filepath=file_path, settings=settings)
    data_norm = data_norm[data_norm.kVp != 0].reset_index(drop=True)  # This is the line removing the rows with 0 kVp

    output = analyze_data(normalized_data=data_norm, settings=settings)

    if settings.output_format in ('dict', 'json'):
        return output
```

Then call this `new_main` function instead of the `main` function in your code.

**Comment by gustavega** [comment]
Hi i try the script but send me errors i dont know if i do correct. in the file main.py i modified lines but show errors. I need help!! thanks

**Comment by BwKodex** [comment]
Hi @gustavega,
What errors do you get?

**Comment by gustavega** [comment]
the same errors i think is with when rewrite code main i thin do wrong. I think when rewrite main and call new_main do wrong . 
for example i rewrite main.py with the corrections 
from typing import Optional, Union

from pyskindose import PyskindoseSettings, analyze_data
from pyskindose.helpers.parse_settings_to_settings_class import parse_settings_to_settings_class
from pyskindose.helpers.read_and_normalize_rdsr_data import read_and_normalise_rdsr_data


def new_main(file_path: Optional[str] = None, settings: Union[str, dict, PyskindoseSettings] = None):
    settings = parse_settings_to_settings_class(settings=settings)

    data_norm = read_and_normalise_rdsr_data(rdsr_filepath=file_path, settings=settings)
    data_norm = data_norm[data_norm.kVp != 0].reset_index(drop=True)  # This is the line removing the rows with 0 kVp

    output = analyze_data(normalized_data=data_norm, settings=settings)

    if settings.output_format in ('dict', 'json'):
        return output

i my file main.py the line 
from pyskindose import PyskindoseSettings, analyze_data  the error is the funtion PyskindoseSettings not recognize 
thanks

**Comment by BwKodex** [comment]
Hi again @gustavega,
I see that I might, mistakenly, have added the import path for the `PyskindoseSettings` from the imminent update where we've made it easier to access. I think you could try to change the import statement for the `PyskindoseSettings` to be on a separate row from the `analyze_data` import and write it like

```python
from pyskindose.settings import PyskindoseSettings
```

Please let me know how it goes.

**Comment by BwKodex** [comment]
There is now a [Getting started section](https://pyskindose.readthedocs.io/en/latest/getting_started/getting_started.html) live in the PySkinDose documentation. I'm closing this issue as users can go there to find usage instructions
